DROP DATABASE IF EXISTS greatBayDB;

CREATE DATABASE greatBayDB;

USE greatBayDB;

CREATE TABLE listItems (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
item VARCHAR(40),
category VARCHAR(40),
bid DECIMAL(10, 2) NOT NULL,
PRIMARY KEY(id)
);

SELECT * FROM listItems;